# Generated by Django 2.2.5 on 2019-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190923_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='contact',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
