# Generated by Django 2.2.5 on 2019-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190923_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
