# Generated by Django 2.2.5 on 2019-09-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190923_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
