# Generated by Django 2.2.5 on 2019-09-23 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190923_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 4, 49, 56, 795567, tzinfo=utc)),
        ),
    ]
