# Generated by Django 2.2.5 on 2019-09-23 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190923_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
